### ISSUE TITLE
Ordering items and categories on the README

### ISSUE THREAD

**Issue by kg583** [TI-Toolkit/awesome-ti-docs#5]
Currently, the README is sorted first by category, then alphabetically. There has been suggestion to instead order things based on predicated relevance; e.g., put 83pa28d higher up in its category than the direct USB docs.

**Alphabetical Ordering**
- Consistent, objective, good for those in search of a particular tool
- Poor for those just starting out, made somewhat moot by Ctrl+F

**Relevance Ordering**
- Good for those just starting out
- Inherently subjective and therefore potentially drama-inducing

A proposed middle ground would be creating a new category at the top of the page for links useful to anyone wanting to get into calculator coding. All such links would still appear on the rest of the page. The other categories would remain alphabetical.

On that note, its also worth discussing which categories should/should not exist and how they're ordered. Too few categories makes searching within a topic harder, while too many could become granular and repetitive (i.e. more tools spanning multiple categories when they don't really need to).

For reference, the current categories are **ASM, TI-BASIC, C/C++, Hardware, Tools, Emulators, Other** (in that order). The largest are **ASM** and **Tools**, while the shortest are **C/C++** and **Other**. The order is rather arbitrary, though not bad.

**Comment by rpitasky** [comment]
I like the idea of having sections based on user wants; "I want to...", and then a list of likely wants. 

It's probably worth enumerating the most common ones, regardless of if we do this, because it would likely inform any organizational strategy.

**Comment by kg583** [comment]
(suggestions from Discord)

## I want to...

- **...learn TI-BASIC**
  - TI|BD, code fragments, useful routines, 84+CE catalog
- **...learn ASM**
  - 83pa28d, (e)z80 docs, (e)z80 opcode table
- **...use the CE toolchain**
  - CE toolchain, CEmu, Git guide
- **...run programs on my calculator**
  - arTIfiCE, TILP, ticalc, Cemetech, TI-Planet (last three should be added to the docs as a whole)
- **...write and run programs on my computer**
  - CEmu, Firebird, SourceCoder, Project Builder, TokenIDE

**Comment by rpitasky** [comment]
<sup><sub>Gosh I spent far too long trying to match that formatting before I realized it was bolded</sub></sup>
Perhaps also 

* **...learn more about the hardware of my calculator**

  * WikiTI, Hardware Revisions sheet

**Comment by kg583** [comment]
> I also think `...use the CE toolchain` warrants some explanation and also links to resources for learning C (any suggestions for good ones to link?), like:
> 
> * **...use the CE toolchain, to write programs for my calculator in C**
>   
>   * CE toolchain, CEmu, Git guide, `insert C programming language guide here`

I agree, this is better, though one might even just say "write programs for my calculator in C" and let the toolchain speak for itself for the sake of brevity.

**Comment by Legend-of-iPhoenix** [comment]
Great idea.

I think this is more or less actionable now. I'm personally a bit sick of writing prose and instructions, having spent the past several days writing things, so I offer this up for anyone who would like to do it.

**Comment by rpitasky** [comment]
Great idea.

I think this is more or less actionable now. I'm personally a bit sick of writing prose and instructions, having spent the past several days writing things, so I offer this up for anyone who would like to do it.
