### ISSUE TITLE
83pa28d links/versions

### ISSUE THREAD

**Issue by tari** [TI-Toolkit/awesome-ti-docs#8]
I think the current links to 83pa28d are weird:

> [Learn TI-83+ Assembly in 28 Days](https://tutorials.eeems.ca/ASMin28Days/welcome.html) ([mirror](https://taricorp.gitlab.io/83pa28d/index.html))

1. Although it's generally worthwhile to have a link to a version that can be viewed directly (Eeems' version does that okay), it also seems worth linking to the [original source on ticalc](https://www.ticalc.org/archives/files/fileinfo/268/26877.html).
2. I don't think it's correct to refer to my version (on gitlab.io) as a mirror; it's meant to be an updated and more friendly version. In particular, it now embeds a modern instruction set reference and in-browser assembler as well as having been updated to fix various incorrect statements and make everything easier to navigate.

I would tend to say that my version is a better choice to present as the primary, though clearly that's somewhat biased as I'm the owner of that version's repository. In any case, I don't think it's correct to call it a mirror.

**Comment by adriweb** [comment]
That's totally fair. How about this?

[Learn TI-83+ Assembly in 28 Days](https://taricorp.gitlab.io/83pa28d/index.html) (modernized version) &bull; Original version: [on ticalc.org](https://www.ticalc.org/archives/files/fileinfo/268/26877.html), and [web-hosted](https://tutorials.eeems.ca/ASMin28Days/welcome.html).
